### ISSUE TITLE
PSX issue

### ISSUE THREAD

**Issue by iamvillain** [Ramaerel/emulatorjs-GameLibrary#3]
Hi there! I seem to be having an issue loading psx roms from the server, I continually get Network Error under any of the formats I tried and the rest of the games from other systems show, any ideas? thanks

**Comment by Ramaerel** [comment]
I'll take a look in the morning, I think I know what it might be. Thank you!

**Comment by Ramaerel** [comment]
This should be fixed now. Add .psx before your extensions (Eg. Crash Bandicoot.psx.bin), and you'll need to create a bios folder and add a ps1 bios to it called psx.bin

Also, as a heads up: I would recommend making your psx roms into zips as per this issue I posted in emulatorJS: https://github.com/ethanaobrien/emulatorjs/issues/157

**Comment by Ramaerel** [comment]
Just let me know if you have more issues and I'll reopen :)
