### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by webysther** [Ramaerel/emulatorjs-GameLibrary#5]
Maybe use this as boilerplate: https://github.com/unclebacon-live/cartridge

![image](https://github.com/Ramaerel/emulatorjs-GameLibrary/assets/750007/4bc2413e-6507-48b2-a8f4-9efcfd714416)

And the LSIO as model for the admin and frontend: https://github.com/linuxserver/emulatorjs

![image](https://github.com/Ramaerel/emulatorjs-GameLibrary/assets/750007/d3d5d029-7ac3-4943-b2d0-1c259cef8873)

**Comment by webysther** [comment]
The second one use a few elements of emulatorjs but they move to libreretro to gain more support for more games, I think the great was libretro (MAME and old stuff) + play! (PS2) + emulatorjs (middle range)

**Comment by Ramaerel** [comment]
I might check out you first suggestion but I won't be doing anything similar to Linuxserver's ejs. Amongst other things, I want this to be as drag-and-drop as possible. 

That said, I haven't had time nor motivation to work on this. I might revisit it again to give it some sort of facelift

Edit:
I checked out the first one. I can use it for inspiration, I might be able to make something

**Comment by webysther** [comment]
Just out of curious, why "I want this to be as drag-and-drop as possible"? I don't have XP with emulator just looking around to find a futureproof and longterm option for my old days few games.

**Comment by Ramaerel** [comment]
My thinking is there's plenty of ways to set something like this up for the technically inclined, such as linuxserver's emulatorjs, webretro, ethanobrien's emulatorjs etc

And while there definitely exists options for people who don't want to go through all the hassle of hosting like afterplay, I thought this would be a nice middleground.

Besides that, outside of the initial version someone asked for, it's been more of a project for myself. Gives me something to do when I have too much downtime and get bored
