### ISSUE TITLE
upload file bug.

### ISSUE THREAD

**Issue by rexhang** [Ramaerel/emulatorjs-GameLibrary#7]
upload.php file line 58 is missing a } symbol, please improve it

**Comment by rexhang** [comment]
Please set php.ini

```php
file_uploads=On
upload_tmp_dir="D:\yourserverClient\tmp"
upload_max_filesize = 100M
post_max_size=100M
```

**Comment by rexhang** [comment]
Support multiple files, the maximum total capacity is 100mb

**Comment by rexhang** [comment]
> Support multiple files, the maximum total capacity is 100mb

Because it is multiple files but only calls the single upload interface

**Comment by Ramaerel** [comment]
I'll go and fix the issue on line 58 now, but I won't do anything for the php.ini - As far as I am aware that's kept elsewhere usually (As in, not the directory the webpage is kept in) so cannot be overwritten without replacing/editing the file in that other location. That's on the hosts.

As for the comment on the upload, do you know of a better way to handle the upload? I'm rewriting big chunks of this project again, so I'll happily improve on that if you have advice.

Keep in mind that programming as a whole is just a hobby for me; While I do spare as much time as I can to this and other projects, it is not a lot of time.
